# Generated by Django 5.0.7 on 2024-10-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_alter_addcourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course',
            field=models.CharField(choices=[('AOOP', 'Advanced Object-Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('OS', 'Operating Systems'), ('SIL', 'Social Immersive Learning')], max_length=50),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='section',
            field=models.CharField(choices=[('S11', 'Section S11'), ('S12', 'Section S12'), ('S13', 'Section S13'), ('S14', 'Section S14'), ('S15', 'Section S15'), ('S21', 'Section S21'), ('S22', 'Section S22'), ('S23', 'Section S23'), ('S24', 'Section S24'), ('S25', 'Section S25')], max_length=50),
        ),
    ]
